apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: wait-for-services
          image: busybox
          command: [ "/bin/sh","-c" ]
          args: [ "until echo 'Esperando a que oracle este disponible.' && nc -vz -w 2 oracle-service 1521 && echo 'Esperando a que redis este disponible.' && nc -vz -w 2 redis-service 6379; do echo 'Volviendo a intentar...'; sleep 2; done;" ]
      containers:
        - name: backend
          image: gcr.io/drivehub-iesmm/backend:latest
          resources:
            requests:
              memory: "2Gi"
              cpu: "4"
            limits:
              memory: "4Gi"
              cpu: "4"