apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  ports:
    - name: nginx-http
      port: 80
      targetPort: 80
    - name: nginx-https
      port: 443
      targetPort: 443
  selector:
    app: nginx