apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  annotations:
    cloud.google.com/load-balancer-ipv4: "34.175.51.197" # Usar siempre esta IP para el despliegue en GCP
spec:
  type: LoadBalancer
  loadBalancerIP: "34.175.51.197"
  ports:
    - name: nginx-http
      port: 80
      targetPort: 80
    - name: nginx-https
      port: 443
      targetPort: 443
  selector:
    app: nginx